.Dd September 29, 2021
.Dt S6-FTRIG-WAIT 8
.Os
.Sh NAME
.Nm s6-ftrig-wait
.Nd subscribe to an
.Xr s6-fifodir 7
and wait for a pattern of events to occur on this fifodir
.Sh SYNOPSIS
.Nm
.Op Fl t Ar timeout
.Ar fifodir
.Ar regexp
.Sh DESCRIPTION
.Nm
subscribes to
.Ar fifodir .
.Pp
It waits for the series of events received on
.Ar fifodir
to match
.Ar regexp .
.Ar regexp
must be an Extended Regular Expression[1].
.Pp
When the series of read events matches
.Ar regexp ,
.Nm
prints the last event it received to stdout (one byte followed by a newline),
then exits 0.
.Sh OPTIONS
.Bl -tag -width x
.It Fl t Ar timeout
If the events on
.Ar fifodir
have not matched
.Ar regexp
after
.Ar timeout
milliseconds, print an error message on stderr and exit 1.
By default,
.Nm
waits indefinitely for a matching series of events.
.El
.Sh SEE ALSO
.Xr s6-cleanfifodir 8 ,
.Xr s6-ftrig-listen 8 ,
.Xr s6-ftrig-listen1 8 ,
.Xr s6-ftrig-notify 8 ,
.Xr s6-ftrigrd 8 ,
.Xr s6-mkfifodir 8
.Pp
[1]
.Lk https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/s6/s6-ftrig-wait.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
