.Dd September 29, 2021
.Dt S6-FGHACK 8
.Os
.Sh NAME
.Nm s6-fghack
.Nd an anti-backgrounding tool
.Sh SYNOPSIS
.Nm
.Ar prog...
.Sh DESCRIPTION
.Nm
opens a lot of file descriptors (all writing to a single pipe).
.Pp
Then it forks and executes
.Ar prog... .
.Pp
If something gets written on one of those descriptors, it's a bug in
.Ar prog .
.Nm
then complains and exits 102.
.Pp
Unless
.Ar prog...
goes out of its way to close descriptors it does not know about,
.Nm
is able to detect when
.Ar prog...
exits.
It exits with the same exit code (or 111 if
.Ar prog...
has crashed).
.Pp
.Nm
is what it says: a hack.
Ideally, you should never have to use it.
It is only useful when you want to supervise a daemon that does not
provide a
.Dq stay in the foreground
option; and even then, the right thing is to report this as a bug to
the daemon author and have it fixed.
.Sh SEE ALSO
.Xr s6-applyuidgid 8 ,
.Xr s6-envdir 8 ,
.Xr s6-envuidgid 8 ,
.Xr s6-setsid 8 ,
.Xr s6-setuidgid 8 ,
.Xr s6-softlimit 8 ,
.Xr s6-tai64n 8 ,
.Xr s6-tai64nlocal 8
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/s6/s6-fghack.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
